steps:
- name: 'node'
entrypoint: 'npm'
args: ['install']
- name: 'node'
entrypoint: 'npm'
args: ["run", "create-env"]
env:
- 'SESSION_SERVER=${_SESSION_SERVER}'
- 'JWT_PUBLIC_KEY=${_JWT_PUBLIC_KEY}'
- 'JWT_PRIVATE_KEY=${_JWT_PRIVATE_KEY}'
- 'UI_SERVER=${_UI_SERVER}'
- name: "gcr.io/cloud-builders/gcloud"
args: ["app", "deploy"]
timeout: "1600s"